#!/bin/bash

if [ $# -lt 1 ]; then
  echo "Usage: enc src dst" >&2
  exit 1
fi
src="$1"
dst="${2:-$(basename "$src").tar.enc}"

tar cf - "$src" \
  | openssl enc -e \
    -aes-256-cbc \
    -md sha512 \
    -pbkdf2 \
    -iter 100000 \
    -salt \
    -out "$dst"
