#!/bin/bash

spack_user_root=${SPACK_ROOT:-"${HOME}/.cache/spack"}

if [ -s "${spack_user_root}" ]; then
  cd "${spack_user_root}"
  git pull
else
  git clone https://github.com/spack/spack.git "${spack_user_root}"
fi
