# history
HISTCONTROL=ignoreboth
HISTSIZE=10000
HISTFILESIZE=20000
HISTTIMEFORMAT='%F %T '
shopt -s histappend

# function

# alias
if [ -f ~/.bash_aliases ]; then
  source ~/.bash_aliases
fi

# completion
if [ -f ~/.bash_completion ]; then
  source ~/.bash_completion
fi

# mise
if [ -f ~/.local/bin/mise ]; then
  eval "$(~/.local/bin/mise activate bash)"
fi
